name: Build & Deploy

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH Configuration
        run: |
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
          echo "SSH_USERNAME: ${{ secrets.SSH_USERNAME }}"
          # Avoid printing the actual key, as it's sensitive information
          echo "SSH_KEY: [REDACTED]"

      - name: Check if PR is merged to main
        id: pr-merged-check
        run: echo "merged=true" >> $GITHUB_ENV
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true

      - name: Deploy Bootstrap 5 static webpage for my-site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            if [ "${{ env.merged }}" == "true" ]; then
              cd /var/www/my-site
              git pull
              echo 'Deployment successful to Digital Ocean'
            else
              echo 'Not a merged pull request to main; deployment skipped'
            fi
